import { useEffect, useState } from "react";
import { FileBarChart, AlertCircle } from "lucide-react";
import { Card, Eyebrow, SectionTitle, Button } from "../components/ui";
import { doc, onSnapshot } from "firebase/firestore";
import { db } from "../lib/firebase";
import { useAuth } from "../lib/AuthContext";
import { callApi } from "../lib/api";

type Period = "daily" | "weekly" | "monthly";
type Block = { label: string; items: string[] };
type Report = { blocks: Block[]; grounded: boolean };

const TABS: { key: Period; label: string }[] = [
  { key: "daily", label: "Daily" },
  { key: "weekly", label: "Weekly" },
  { key: "monthly", label: "Monthly" },
];

function blurbFor(period: Period) {
  const now = new Date();
  if (period === "daily")
    return now.toLocaleDateString([], { weekday: "long", month: "long", day: "numeric" });
  if (period === "monthly")
    return now.toLocaleDateString([], { month: "long", year: "numeric" });
  const start = new Date(now);
  start.setDate(now.getDate() - 6);
  const opts = { month: "short", day: "numeric" } as const;
  return `Week of ${start.toLocaleDateString([], opts)} – ${now.toLocaleDateString([], opts)}`;
}

export default function Reports() {
  const { user } = useAuth();
  const [tab, setTab] = useState<Period>("weekly");
  const [cache, setCache] = useState<Record<string, Report>>({});
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!user) return;

    if (cache[tab]) {
      setState("ready");
      return;
    }

    let active = true;
    setState("loading");
    setError(null);

    // Try to load from cache first (generated by scheduled function)
    const unsubscribe = onSnapshot(
      doc(db, "users", user.uid, "state", `reports_${tab}`),
      (snap) => {
        if (!active) return;

        if (snap.exists()) {
          const data = snap.data() as any;
          setCache((c) => ({
            ...c,
            [tab]: { blocks: data.blocks ?? [], grounded: data.grounded ?? true },
          }));
          setState("ready");
        } else {
          // No cached report, generate on-demand
          callApi<{ blocks: Block[]; grounded: boolean }>("generateReport", { period: tab })
            .then((r) => {
              if (!active) return;
              setCache((c) => ({ ...c, [tab]: { blocks: r.blocks ?? [], grounded: r.grounded } }));
              setState("ready");
            })
            .catch((e: any) => {
              if (!active) return;
              setError(e?.message ?? "Couldn't build the report.");
              setState("error");
            });
        }
      }
    );

    return () => {
      active = false;
      unsubscribe();
    };
  }, [tab, user]);

  const report = cache[tab];

  return (
    <div className="mx-auto max-w-7xl">
      <SectionTitle
        title="Intelligence Reports"
        sub="Your business, summarized from your real email and meetings. Daily priorities, weekly momentum, monthly strategy."
      />

      <div className="mb-5 flex gap-1 rounded-xl border border-sand bg-cream p-1">
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`flex-1 rounded-lg px-4 py-2 text-sm font-semibold transition ${
              tab === t.key ? "bg-brown text-cream" : "text-brown-mid hover:bg-clay-light"
            }`}
          >
            {t.label} Report
          </button>
        ))}
      </div>

      <Card>
        <Eyebrow>
          {TABS.find((t) => t.key === tab)?.label} Report · {blurbFor(tab)}
        </Eyebrow>

        {state === "loading" && (
          <p className="mt-4 text-sm text-brown-mid">Reading your email and meetings, writing the report…</p>
        )}

        {state === "error" && (
          <div className="mt-4 flex items-start gap-2">
            <AlertCircle size={16} className="mt-0.5 text-copper" />
            <div>
              <p className="text-sm text-brown">{error}</p>
              <Button variant="secondary" className="mt-3" onClick={() => setTab(tab)}>
                <FileBarChart size={15} /> Try again
              </Button>
            </div>
          </div>
        )}

        {state === "ready" && report && report.grounded === false && (
          <p className="mt-4 text-sm text-brown-mid">
            Connect Gmail and sync your meetings first, then your reports build themselves from the
            real activity.
          </p>
        )}

        {state === "ready" && report && report.grounded !== false && (
          <div className="mt-3 grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
            {report.blocks.length === 0 && (
              <p className="text-sm text-brown-mid">Nothing to report for this period yet.</p>
            )}
            {report.blocks.map((b) => (
              <div key={b.label}>
                <p className="mb-2 text-sm font-bold text-clay">{b.label}</p>
                <ul className="space-y-1.5">
                  {b.items.map((it, i) => (
                    <li key={i} className="flex gap-2 text-sm leading-snug text-brown">
                      <span className="text-clay">›</span>
                      {it}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
